// <auto-generated />
namespace WcfServices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removed_Subject_and_Class_Coulmn_Attendance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_Subject_and_Class_Coulmn_Attendance));
        
        string IMigrationMetadata.Id
        {
            get { return "202204021625552_removed_Subject_and_Class_Coulmn_Attendance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
